version: "3.9"

services:
  web:
    image: lecastro1993/app-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.3-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
    networks:
      - web_network

  mysql:
    restart: always
    hostname: "mysql"
    image: mysql:8.0.19
    container_name: "mysql"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - web_network

  redis:
    hostname: "redis"
    image: redis:alpine3.15
    container_name: "redis"
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes:
      - cache:/data
    networks:
      - web_network

volumes:
  database:
    name: mysql_db_vol
  cache:
    name: redis_cache_vol

networks:
  web_network:
    driver: bridge